<% require "dotenv"; Dotenv.load(".env") %>

service: illustration-portal

image: mousu-a/illustration_portal

servers:
  web:
    - 52.196.110.227

proxy:
  ssl: true
  host: esipo.me

deploy_timeout: 120

registry:
  server: ghcr.io
  username: mousu-a
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - ILLUSTRATION_PORTAL_DATABASE_PASSWORD
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: illustration-portal-db

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu

accessories:
  db:
    image: postgres:18
    roles:
      - web
    env:
      clear:
        POSTGRES_DB: illustration_portal_production
        POSTGRES_USER: illustration_portal
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql
